### ISSUE TITLE
Add descriptions for timeslots

### ISSUE THREAD

**Issue by fahrstuhl** [fahrstuhl/pymodoroserver#3]
#1 and #2 would need some way to label how a timeslot was spent. Maybe look at what data a single toggl timeslot contains? I think something like this should work fine:

YAML:
```yaml
description: A sentence or two what work was being done
tags: [ a, list of, tags ]
category: The bigger picture / category this work belongs to
```

Inline:
`The description just contains #tag1, #tag2, #longer_tag3 and @category.`
